algoritmo "Ex 8"
// Função : Converter dolares em reais
// Autor :  Vincius Luiz
// Data : 25/09/2025
// Seção de Declarações 
var

reais , dolar , us  : real

inicio
// Seção de Comandos 

escreval("Quantos dolares você possui $ : ")
leia(dolar)

escreval("Qual a cotação R$ ?")
leia(reais)


us <- dolar * reais
escreva("Voce possui $ : " , us)

us <- dolar - us
escreva(" Sobrou : $ " , dolar)

// converter reais em dolares e dizer quantos sobraram

fimalgoritmo

