algoritmo "Ex 9"
// Função : Rendimento de dinheiro em 1 mes no banco
// Autor : Vinicius Luiz
// Data : 25/09/2025
// Seção de Declarações 
var
deposito , valorfinal, mes : real
inicio
// Seção de Comandos 

escreval("Quantos R$ serão depositados? :")
leia(deposito)

valorfinal <- deposito * (1 + 0.007)

escreva("Valor final após 1 mês : ", "R$" ,  valorfinal)

// O rendimento do dinheiro depositado com um juros de 0, 70 %  em 1 mes

fimalgoritmo


