algoritmo "Ex23"
// Função :
// Autor : Vinicius Luiz
// Data : 13/10/2025
// Seção de Declarações 
var
numero :  inteiro
inicio
// Seção de Comandos

escreval("Digite um número : ")
leia(numero)

se (numero > 80) entao
   escreval("o número é maior que 80 ")
   fimse

se (numero < 25) entao
   escreval("O número é menor que 25 ")
   fimse
   
se (numero = 40) entao
   escreval("O número é igual a 40 ")
   
fimse
   





 
fimalgoritmo
