algoritmo "Ex18"
// Função : Ler o nome de 75 pessoas e informar se é maior de idade ou menor
// Autor : Vinicius Luiz
// Data : 30/09/2025
// Seção de Declarações 
var
i, idade: inteiro
// Seção de Comandos 

para i de 1 ate 75 faca
   escreva("Digite a idade da ", i, "ª pessoa: ")
   leia(idade)

   se (idade >= 18) entao
      escreval("Pessoa ", i, ": MAIOR DE IDADE")
   senao
      escreval("Pessoa ", i, ": MENOR DE IDADE")
   fimse
fimpara





fimalgoritmo


