algoritmo "ex 14"
// Função :
// Autor : Vinicius Luiz
// Data : 29/09/2025
// Seção de Declarações 
var
n1 , n2 , n3 : real
inicio
// Seção de Comandos 

escreval("Digite um numero : ")
leia(n1)

escreval("Digite outro numero : ")
leia(n2)

se n1 > n2 entao
 escreval("O número ", n1 , " é maior que , ", n2)
 senao
 escreval("o número ", n2 , " é maior que , ", n1)
fimse


fimalgoritmo
