algoritmo "Ex10"
// Função : 5 prestacoes de juros
// Autor :  Vinicius Luiz
// Data : 26/09/2025
// Seção de Declarações
var

prestacao , valor : real

inicio
// Seção de Comandos

escreval("Digite o valor da compra R$ : ")
leia(valor)


prestacao <- valor / 5

escreval("O valor de cada prestação é: R$ ", prestacao:0:2)

// calular 5 prestacoes sem juros de um produto

fimalgoritmo

