algoritmo "ex1"
// Função : ler dois numeros e somar
// Autor :  Vinicius Luiz
// Data : 23/09/2025
// Seção de Declarações 
var
numero1, numero2 : inteiro


inicio
// Seção de Comandos 


// a funcao e ler dois numeros, somar e mostrar o resultado
escreval("Digite o numero1 : ")
leia(numero1)
escreval("Digite o numero2 : ")
leia(numero2)


escreval("A soma é:" , numero1 + numero2)
fimalgoritmo

