algoritmo "Ex7"
// Função : converter graus celsius em fareinheirt
// Autor : Vinicius Luiz
// Data : 25/09/2025
// Seção de Declarações 
var
f, c : real

inicio
// Seção de Comandos 

escreval("Digite quantos celsius vc quer converter : ")
leia(c)

f <- (9 * c + 160) /5
escreval("A conversão para faren é : " , f)

// converter os graus celsius informado em fareinheirt



fimalgoritmo



